<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Supritha Ramakrishna Maiya (35196726)">
<meta name="dcterms.date" content="2026-06-12">

<title>ETC5512: Assignment 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="assignment4_35196726_files/libs/clipboard/clipboard.min.js"></script>
<script src="assignment4_35196726_files/libs/quarto-html/quarto.js"></script>
<script src="assignment4_35196726_files/libs/quarto-html/popper.min.js"></script>
<script src="assignment4_35196726_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="assignment4_35196726_files/libs/quarto-html/anchor.min.js"></script>
<link href="assignment4_35196726_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="assignment4_35196726_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="assignment4_35196726_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="assignment4_35196726_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="assignment4_35196726_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#melbournes-café-scene" id="toc-melbournes-café-scene" class="nav-link active" data-scroll-target="#melbournes-café-scene">Melbourne’s Café Scene</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ETC5512: Assignment 4</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Supritha Ramakrishna Maiya (35196726) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 12, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="melbournes-café-scene" class="level1">
<h1>Melbourne’s Café Scene</h1>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Data Details</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Blog Post</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">Behind the Scenes</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false" href="">AI Acknowledgement</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<section id="question-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1">Question 1</h3>
<p><em>What is the question you are aiming to answer in your blog post? (You may have multiple sub-questions.) Share why you chose this question.</em></p>
<p>How has Melbourne’s café and dining scene evolved over two decades (2002–2024), and is seating capacity distributed equitably across suburbs?</p>
<p>This question is explored through three sub-questions:</p>
<ul>
<li>How has Melbourne’s café scene grown from 2002 to 2024, and which suburbs have consistently dominated by seating capacity?</li>
<li>Did COVID-19 (2020–2021) cause a measurable shift from indoor to outdoor seating across Melbourne?</li>
<li>Do higher-income suburbs have disproportionately more seating capacity per resident?</li>
</ul>
<p>I chose this question because I come from Bangalore - also a coffee city. South Indian filter coffee is famous among Bangaloreans, and in recent years Bangalore’s café culture has expanded far beyond that signature drink, with roasters like Blue Tokai, Benki Coffee, and Hatti Kappi redefining the scene.</p>
<p>Moving to Melbourne, a city whose café culture is part of its global identity, I was curious whether that reputation is actually backed by data — and whether it extends equally across the city.</p>
</section>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2</h3>
<p><em>What data will you be using to answer that question? Explain why this data is suitable for the task. This means make clear the type of data (census, sample, experimental), data licence, data limitations and any ethical considerations, including those related to data privacy. The relevant details here will depend on the data you choose and the analysis you perform.</em></p>
<p>Dataset 1 can be downloaded from the City of Melbourne Open Data Portal at data.melbourne.vic.gov.au, searching for “Café, Restaurant and Bistro Seats.”</p>
<p><strong>Dataset 1: Café, Restaurant and Bistro Seats — City of Melbourne CLUE</strong></p>
<ul>
<li><strong>Source:</strong> City of Melbourne Open Data Portal</li>
<li><strong>Type:</strong> Census</li>
<li><strong>Licence:</strong> Creative Commons Attribution 4.0 International (CC BY 4.0)</li>
<li><strong>Coverage:</strong> 2002–2024</li>
<li><strong>Variables used:</strong> Census year, CLUE small area (suburb), Trading name, Business address, Seating type (Indoor/Outdoor), Number of seats, Longitude, Latitude</li>
<li><strong>Limitations:</strong> Coverage is limited to the City of Melbourne LGA only — it does not capture broader metropolitan Melbourne. Seat counts reflect licensed capacity, not actual usage. Some records in early years (particularly 2002) have missing coordinate data.</li>
<li><strong>Ethics:</strong> No personal data is involved. All records are at the business level only.</li>
</ul>
<p>Datasets 2–4 are available from the ABS Census DataPacks page. Select 2021 Census, General Community Profile, Victoria, SA2. Download G01 and G02 CSV files and the ASGS metadata Excel file.</p>
<p><strong>Dataset 2: ABS Census 2021 — General Community Profile (G02), Victoria, SA2</strong></p>
<ul>
<li><strong>Source:</strong> Australian Bureau of Statistics Census DataPacks</li>
<li><strong>Type:</strong> Census — a complete population count</li>
<li><strong>Licence:</strong> Creative Commons Attribution 4.0 International (CC BY 4.0)</li>
<li><strong>Variables used:</strong> Median weekly household income (<code>Median_tot_hhd_inc_weekly</code>)</li>
<li><strong>Limitations:</strong> 2021 Census data may not perfectly reflect 2024 suburb demographics. Also,SA2 boundaries do not align with CLUE small areas.</li>
<li><strong>Ethics:</strong> Only aggregate-level data used. No individual records involved.</li>
</ul>
<p><strong>Dataset 3: ABS Census 2021 — General Community Profile (G01), Victoria, SA2</strong></p>
<ul>
<li><strong>Source:</strong> Australian Bureau of Statistics Census DataPacks</li>
<li><strong>Type:</strong> Census</li>
<li><strong>Licence:</strong> Creative Commons Attribution 4.0 International (CC BY 4.0)</li>
<li><strong>Variables used:</strong> Total population (<code>Tot_P_P</code>)</li>
<li><strong>Limitations:</strong> Same as Dataset 2.</li>
<li><strong>Ethics:</strong> Aggregate data only.</li>
</ul>
<p><strong>Dataset 4: ABS 2021 Census — Geographic Descriptor File</strong></p>
<ul>
<li><strong>Source:</strong> Australian Bureau of Statistics Census DataPacks</li>
<li><strong>Type:</strong> Reference/lookup file</li>
<li><strong>Licence:</strong> Creative Commons Attribution 4.0 International (CC BY 4.0)</li>
<li><strong>Variables used:</strong> SA2 codes and names for joining G01/G02 to suburb names</li>
</ul>
<p><strong>Dataset 5: City of Melbourne — Suburb Boundary Shapefile</strong></p>
<ul>
<li><strong>Source:</strong> City of Melbourne Open Data Portal</li>
<li><strong>Type:</strong> Geospatial reference file</li>
<li><strong>Licence:</strong> Creative Commons Attribution 4.0 International (CC BY 4.0)</li>
<li><strong>Variables used:</strong> <code>mccid_int</code> (postcode), polygon geometry</li>
<li><strong>Limitations:</strong> No suburb name labels(postcode to suburb name mapping was done manually).</li>
<li><strong>Ethics:</strong> No personal data involved.</li>
</ul>
</section>
<section id="question-3" class="level3">
<h3 class="anchored" data-anchor-id="question-3">Question 3</h3>
<p><em>Describe the steps to download your data and any steps to process your data for your analysis. Save your raw and processed data.</em></p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load raw CLUE café data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>clue_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data/raw/cafes-and-restaurants-with-seating-capacity.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>cafes <span class="ot">&lt;-</span> clue_raw <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Industry (ANZSIC4) description</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Cafes and Restaurants"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Save filtered data</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(cafes, <span class="fu">here</span>(<span class="st">"data/processed/cafes_filtered.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The raw CLUE dataset contains multiple industry types. I filtered by the ANZSIC4 code “Cafes and Restaurants” only, as other categories (e.g.&nbsp;pubs, fast food) are outside the scope of this analysis.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>suburb_2024 <span class="ot">&lt;-</span> cafes <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Census year</span><span class="st">`</span> <span class="sc">==</span> <span class="dv">2024</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="st">`</span><span class="at">CLUE small area</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_seats =</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">Number of seats</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_seats))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>To enable an equity analysis, median household income and population data were drawn from the ABS 2021 Census. CLUE uses its own suburb naming conventions that differ from ABS SA2 names, a manual look up table is constructed to bridge the two systems, where a CLUE suburb maps to multiple ABS SA2s (e.g.&nbsp;Southbank spans two SA2s), a population-weighted mean income was calculated rather than a simple average.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SA2 lookup</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>sa2_lookup <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">here</span>(<span class="st">"data/raw/Metadata/2021Census_geog_desc_1st_2nd_3rd_release.xlsx"</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sheet =</span> <span class="st">"2021_ASGS_MAIN_Structures"</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ASGS_Structure <span class="sc">==</span> <span class="st">"SA2"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">SA2_CODE_2021 =</span> Census_Code_2021,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">SA2_NAME_2021 =</span> Census_Name_2021)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Income data</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>g02 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data/raw/2021Census_G02_VIC_SA2.csv"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SA2_CODE_2021,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">median_weekly_income =</span> Median_tot_hhd_inc_weekly) <span class="sc">|&gt;</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SA2_CODE_2021 =</span> <span class="fu">as.character</span>(SA2_CODE_2021))</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Population data</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>g01 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data/raw/2021Census_G01_VIC_SA2.csv"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SA2_CODE_2021, <span class="at">population =</span> Tot_P_P) <span class="sc">|&gt;</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SA2_CODE_2021 =</span> <span class="fu">as.character</span>(SA2_CODE_2021))</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Join both to SA2 names</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>abs_data <span class="ot">&lt;-</span> g02 <span class="sc">|&gt;</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(g01, <span class="at">by =</span> <span class="st">"SA2_CODE_2021"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(sa2_lookup, <span class="at">by =</span> <span class="st">"SA2_CODE_2021"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">suburb =</span> SA2_NAME_2021, median_weekly_income, population)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate split Southbank SA2s using population-weighted mean</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>southbank_weighted <span class="ot">&lt;-</span> abs_data <span class="sc">|&gt;</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(suburb, <span class="st">"Southbank"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">suburb =</span> <span class="st">"Southbank"</span>,</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_weekly_income =</span> <span class="fu">weighted.mean</span>(median_weekly_income, population),</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">population =</span> <span class="fu">sum</span>(population)</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>abs_data <span class="ot">&lt;-</span> abs_data <span class="sc">|&gt;</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_detect</span>(suburb, <span class="st">"Southbank"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(southbank_weighted)</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate split CBD SA2s using population-weighted mean</span></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>cbd_weighted <span class="ot">&lt;-</span> abs_data <span class="sc">|&gt;</span></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(suburb, <span class="st">"Melbourne CBD"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">suburb =</span> <span class="st">"Melbourne (CBD)"</span>,</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_weekly_income =</span> <span class="fu">weighted.mean</span>(median_weekly_income, population),</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">population =</span> <span class="fu">sum</span>(population)</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>abs_data <span class="ot">&lt;-</span> abs_data <span class="sc">|&gt;</span></span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_detect</span>(suburb, <span class="st">"Melbourne CBD"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(cbd_weighted)</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate split CBD SA2s using population-weighted mean</span></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>southyarra_weighted <span class="ot">&lt;-</span> abs_data <span class="sc">|&gt;</span></span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(suburb, <span class="st">"South Yarra"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>    <span class="at">suburb =</span> <span class="st">"South Yarra"</span>,</span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_weekly_income =</span> <span class="fu">weighted.mean</span>(median_weekly_income, population),</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>    <span class="at">population =</span> <span class="fu">sum</span>(population)</span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a>abs_data <span class="ot">&lt;-</span> abs_data <span class="sc">|&gt;</span></span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_detect</span>(suburb, <span class="st">"South Yarra"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(southyarra_weighted)</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a><span class="co"># Manual suburb name mapping</span></span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a>name_mapping <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>clue_name,                        <span class="sc">~</span>abs_name,</span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Melbourne (CBD)"</span>,                  <span class="st">"Melbourne (CBD)"</span>,</span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Carlton"</span>,                          <span class="st">"Carlton"</span>,</span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Docklands"</span>,                        <span class="st">"Docklands"</span>,</span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a>  <span class="st">"East Melbourne"</span>,                   <span class="st">"East Melbourne"</span>,</span>
<span id="cb5-73"><a href="#cb5-73" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Kensington"</span>,                       <span class="st">"Kensington (Vic.)"</span>,</span>
<span id="cb5-74"><a href="#cb5-74" aria-hidden="true" tabindex="-1"></a>  <span class="st">"North Melbourne"</span>,                  <span class="st">"North Melbourne"</span>,</span>
<span id="cb5-75"><a href="#cb5-75" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Parkville"</span>,                        <span class="st">"Parkville"</span>,</span>
<span id="cb5-76"><a href="#cb5-76" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Southbank"</span>,                        <span class="st">"Southbank"</span>,</span>
<span id="cb5-77"><a href="#cb5-77" aria-hidden="true" tabindex="-1"></a>  <span class="st">"South Yarra"</span>,                      <span class="st">"South Yarra"</span>,</span>
<span id="cb5-78"><a href="#cb5-78" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Port Melbourne"</span>,                   <span class="st">"Port Melbourne"</span>,</span>
<span id="cb5-79"><a href="#cb5-79" aria-hidden="true" tabindex="-1"></a>  <span class="st">"West Melbourne (Industrial)"</span>,      <span class="st">"West Melbourne - Industrial"</span>,</span>
<span id="cb5-80"><a href="#cb5-80" aria-hidden="true" tabindex="-1"></a>  <span class="st">"West Melbourne (Residential)"</span>,     <span class="st">"West Melbourne - Residential"</span></span>
<span id="cb5-81"><a href="#cb5-81" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-82"><a href="#cb5-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-83"><a href="#cb5-83" aria-hidden="true" tabindex="-1"></a><span class="co"># Build equity dataset</span></span>
<span id="cb5-84"><a href="#cb5-84" aria-hidden="true" tabindex="-1"></a>equity_data <span class="ot">&lt;-</span> suburb_2024 <span class="sc">|&gt;</span></span>
<span id="cb5-85"><a href="#cb5-85" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(name_mapping, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"CLUE small area"</span> <span class="ot">=</span> <span class="st">"clue_name"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-86"><a href="#cb5-86" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(abs_data, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"abs_name"</span> <span class="ot">=</span> <span class="st">"suburb"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-87"><a href="#cb5-87" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(median_weekly_income)) <span class="sc">|&gt;</span></span>
<span id="cb5-88"><a href="#cb5-88" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">seats_per_1000 =</span> (total_seats <span class="sc">/</span> population) <span class="sc">*</span> <span class="dv">1000</span>)</span>
<span id="cb5-89"><a href="#cb5-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-90"><a href="#cb5-90" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(equity_data, <span class="fu">here</span>(<span class="st">"data/processed/cafe_equity_analysis.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="question-4" class="level3">
<h3 class="anchored" data-anchor-id="question-4">Question 4</h3>
<p><em>In your submission, include comprehensive details of the data you used (e.g.&nbsp;read me, meta data file, a data dictionary. This may also include a sample data example if useful.)</em></p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data dictionary CSV</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>data_dict <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">c</span>(<span class="st">"Census year"</span>, <span class="st">"CLUE small area"</span>, <span class="st">"Trading name"</span>, </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Business address"</span>, <span class="st">"Industry (ANZSIC4) description"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Seating type"</span>, <span class="st">"Number of seats"</span>, <span class="st">"Longitude"</span>, <span class="st">"Latitude"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Median_tot_hhd_inc_weekly"</span>, <span class="st">"Tot_P_P"</span>, <span class="st">"SA2_CODE_2021"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>               <span class="st">"SA2_NAME_2021"</span>, <span class="st">"seats_per_1000"</span>),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Dataset =</span> <span class="fu">c</span>(<span class="st">"CLUE"</span>, <span class="st">"CLUE"</span>, <span class="st">"CLUE"</span>, <span class="st">"CLUE"</span>, <span class="st">"CLUE"</span>, <span class="st">"CLUE"</span>, <span class="st">"CLUE"</span>, </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>              <span class="st">"CLUE"</span>, <span class="st">"CLUE"</span>, <span class="st">"ABS G02"</span>, <span class="st">"ABS G01"</span>, <span class="st">"ABS Metadata"</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>              <span class="st">"ABS Metadata"</span>, <span class="st">"Derived"</span>),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Description =</span> <span class="fu">c</span>(<span class="st">"Year of annual business census (2002-2024)"</span>,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Suburb/precinct name within City of Melbourne LGA"</span>,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Business trading name"</span>,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Full street address of business"</span>,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Business industry classification"</span>,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Indoor or outdoor seating"</span>,</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Licensed seating capacity"</span>,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"WGS84 longitude coordinate"</span>,</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"WGS84 latitude coordinate"</span>,</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Median weekly household income by SA2"</span>,</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Total resident population by SA2"</span>,</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"9-digit SA2 geographic code"</span>,</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"SA2 suburb name"</span>,</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Cafe seats per 1000 residents"</span>),</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">Type =</span> <span class="fu">c</span>(<span class="st">"Numeric"</span>, <span class="st">"Character"</span>, <span class="st">"Character"</span>, <span class="st">"Character"</span>, <span class="st">"Character"</span>,</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>           <span class="st">"Character"</span>, <span class="st">"Numeric"</span>, <span class="st">"Numeric"</span>, <span class="st">"Numeric"</span>, <span class="st">"Numeric"</span>,</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>           <span class="st">"Numeric"</span>, <span class="st">"Character"</span>, <span class="st">"Character"</span>, <span class="st">"Numeric"</span>)</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(data_dict, <span class="fu">here</span>(<span class="st">"data/data-dictionary.csv"</span>))</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample data</span></span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>cafes <span class="sc">|&gt;</span> <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>) <span class="sc">|&gt;</span> </span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_csv</span>(<span class="fu">here</span>(<span class="st">"data/sample-clue.csv"</span>))</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>equity_data <span class="sc">|&gt;</span> <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>) <span class="sc">|&gt;</span> </span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_csv</span>(<span class="fu">here</span>(<span class="st">"data/sample-equity.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>metadata <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Attribute =</span> <span class="fu">c</span>(<span class="st">"Source"</span>, <span class="st">"Structure"</span>, <span class="st">"Methodology"</span>, <span class="st">"Topic"</span>, </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Geographic coverage"</span>, <span class="st">"Temporal coverage"</span>, </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Licence"</span>, <span class="st">"Last updated"</span>, <span class="st">"Maintenance"</span>),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Dataset 1 (CLUE)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"City of Melbourne Open Data Portal"</span>, </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Tabular CSV"</span>, </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Annual business census"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Food business seating capacity"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"City of Melbourne LGA"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"2002–2024"</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"CC BY 4.0"</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"2024"</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"City of Melbourne annually"</span>),</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Dataset 2 (ABS G02)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Australian Bureau of Statistics"</span>,</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Tabular CSV"</span>,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"5-yearly population census"</span>,</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Household income"</span>,</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Victoria, SA2 level"</span>,</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"2021"</span>,</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"CC BY 4.0"</span>,</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"2022"</span>,</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"ABS every 5 years"</span>),</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Dataset 3 (ABS G01)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Australian Bureau of Statistics"</span>,</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Tabular CSV"</span>,</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"5-yearly population census"</span>,</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Population counts"</span>,</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Victoria, SA2 level"</span>,</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"2021"</span>,</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"CC BY 4.0"</span>,</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"2022"</span>,</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"ABS every 5 years"</span>),</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Dataset 4 (ASGS)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Australian Bureau of Statistics"</span>,</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Excel lookup"</span>,</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Administrative geography standard"</span>,</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Geographic boundaries"</span>,</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Australia-wide"</span>,</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"2021"</span>,</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"CC BY 4.0"</span>,</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"2022"</span>,</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"ABS every 5 years"</span>),</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Dataset 5 (Postcodes)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"City of Melbourne Open Data Portal"</span>,</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Shapefile"</span>,</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Administrative boundary file"</span>,</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Suburb boundaries"</span>,</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"City of Melbourne LGA"</span>,</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"2003–2011"</span>,</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"CC BY 4.0"</span>,</span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"2011"</span>,</span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"City of Melbourne"</span>)</span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(metadata, <span class="fu">here</span>(<span class="st">"data/metadata.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>CLUE Dataset Variables:</strong></p>
<ul>
<li><strong>Census year</strong> <em>(Numeric)</em>: Year of the annual business census (2002–2024)</li>
<li><strong>CLUE small area</strong> <em>(Character)</em>: Suburb/precinct name within City of Melbourne LGA</li>
<li><strong>Trading name</strong> <em>(Character)</em>: Business trading name</li>
<li><strong>Business address</strong> <em>(Character)</em>: Full street address of business</li>
<li><strong>Industry (ANZSIC4) description</strong> <em>(Character)</em>: Business industry classification</li>
<li><strong>Seating type</strong> <em>(Character)</em>: Indoor or outdoor seating</li>
<li><strong>Number of seats</strong> <em>(Numeric)</em>: Licensed seating capacity</li>
<li><strong>Longitude</strong> <em>(Numeric)</em>: WGS84 longitude coordinate</li>
<li><strong>Latitude</strong> <em>(Numeric)</em>: WGS84 latitude coordinate</li>
</ul>
<p><strong>ABS G02 Variables:</strong></p>
<ul>
<li><strong>Median_tot_hhd_inc_weekly</strong> <em>(Numeric)</em>: Median weekly household income by SA2</li>
</ul>
<p><strong>ABS G01 Variables:</strong></p>
<ul>
<li><strong>Tot_P_P</strong> <em>(Numeric)</em>: Total resident population by SA2</li>
</ul>
<p><strong>ABS Metadata Variables:</strong></p>
<ul>
<li><strong>SA2_CODE_2021</strong> <em>(Character)</em>: 9-digit SA2 geographic code</li>
<li><strong>SA2_NAME_2021</strong> <em>(Character)</em>: SA2 suburb name</li>
</ul>
<p><strong>Derived Variables:</strong></p>
<ul>
<li><strong>seats_per_1000</strong> <em>(Numeric)</em>: Café seats per 1,000 residents (total_seats / population × 1,000)</li>
<li><strong>abs_name</strong> <em>(Character)</em>: Matched ABS SA2 name used to join CLUE suburb to ABS data</li>
<li><strong>median_weekly_income</strong> <em>(Numeric)</em>: Population-weighted median income after SA2 aggregation</li>
<li><strong>population</strong> <em>(Numeric)</em>: Total resident population after SA2 aggregation</li>
</ul>
<p>For full variable definitions see ‘data/data-dictionary.csv’. Sample records from the raw CLUE data and processed equity dataset are available in <code>data/sample-clue.csv</code> and <code>data/sample-equity.csv</code>.</p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<p>Australian Bureau of Statistics. (2021). 2021 Census community profiles: General community profile (G01) [Data set]. <a href="https://www.abs.gov.au/census/find-census-data/datapacks" class="uri">https://www.abs.gov.au/census/find-census-data/datapacks</a></p>
<p>Australian Bureau of Statistics. (2021). 2021 Census community profiles: Selected medians and averages (G02) [Data set]. <a href="https://www.abs.gov.au/census/find-census-data/datapacks" class="uri">https://www.abs.gov.au/census/find-census-data/datapacks</a></p>
<p>Australian Bureau of Statistics. (2021). 2021 Australian Statistical Geography Standard (ASGS) geographic structures [Data file]. <a href="https://www.abs.gov.au/census/find-census-data/datapacks" class="uri">https://www.abs.gov.au/census/find-census-data/datapacks</a></p>
<p>Blue Tokai Coffee Roasters. (n.d.). About us. <a href="https://bluetokaicoffee.com/pages/about-us" class="uri">https://bluetokaicoffee.com/pages/about-us</a></p>
<p>City of Melbourne Open Data Team. (2015). Cafes and restaurants with seating capacity [Data set]. Melbourne Open Data Portal. <a href="https://data.melbourne.vic.gov.au/explore/dataset/cafes-and-restaurants-with-seating-capacity/information/" class="uri">https://data.melbourne.vic.gov.au/explore/dataset/cafes-and-restaurants-with-seating-capacity/information/</a></p>
<p>Hatti Kaapi Food &amp; Beverages. (n.d.). Hatti Kaapi Food &amp; Beverages [Company page]. LinkedIn. <a href="https://www.linkedin.com/company/hatti-kaapi-food-beverages/" class="uri">https://www.linkedin.com/company/hatti-kaapi-food-beverages/</a></p>
</section>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>I grew up in Bangalore,another city that takes its coffee seriously. When I moved to Melbourne, I heard that Melbourne is synonymous with café culture. Is that reputation backed by data?</p>
<p>Using two decades of business census data from the City of Melbourne, this post looks at how the café scene has grown, where it actually lives, what COVID did to it, and whether café access follows wealth.</p>
<section id="the-decline-that-predates-covid" class="level3">
<h3 class="anchored" data-anchor-id="the-decline-that-predates-covid">The decline that predates COVID</h3>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>growth_total <span class="ot">&lt;-</span> cafes <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Census year</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_cafes =</span> <span class="fu">n_distinct</span>(<span class="fu">paste</span>(<span class="st">`</span><span class="at">Trading name</span><span class="st">`</span>, <span class="st">`</span><span class="at">Business address</span><span class="st">`</span>)),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_seats =</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">Number of seats</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Line chart: total seats over time</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(growth_total, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Census year</span><span class="st">`</span>, <span class="at">y =</span> total_seats)) <span class="sc">+</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> <span class="st">"#6F4E37"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">colour =</span> <span class="st">"#6F4E37"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">2002</span>, <span class="dv">2024</span>, <span class="at">by =</span> <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Total Café Seating Capacity in Melbourne (2002–2024)"</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Total Seats"</span>) <span class="sc">+</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment4_35196726_files/figure-html/growth-over-time-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>growth_total <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="st">`</span><span class="at">Census year</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Year"</span>, <span class="st">"Number of Cafés"</span>, <span class="st">"Total Seats"</span>),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">0</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;">Number of Cafés</th>
<th style="text-align: right;">Total Seats</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2002</td>
<td style="text-align: right;">886</td>
<td style="text-align: right;">85349</td>
</tr>
<tr class="even">
<td style="text-align: right;">2003</td>
<td style="text-align: right;">914</td>
<td style="text-align: right;">89736</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2004</td>
<td style="text-align: right;">944</td>
<td style="text-align: right;">93258</td>
</tr>
<tr class="even">
<td style="text-align: right;">2005</td>
<td style="text-align: right;">1025</td>
<td style="text-align: right;">102271</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2006</td>
<td style="text-align: right;">1065</td>
<td style="text-align: right;">104592</td>
</tr>
<tr class="even">
<td style="text-align: right;">2007</td>
<td style="text-align: right;">1111</td>
<td style="text-align: right;">106533</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2008</td>
<td style="text-align: right;">1169</td>
<td style="text-align: right;">111081</td>
</tr>
<tr class="even">
<td style="text-align: right;">2009</td>
<td style="text-align: right;">1253</td>
<td style="text-align: right;">118420</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2010</td>
<td style="text-align: right;">1301</td>
<td style="text-align: right;">116700</td>
</tr>
<tr class="even">
<td style="text-align: right;">2011</td>
<td style="text-align: right;">1363</td>
<td style="text-align: right;">123649</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2012</td>
<td style="text-align: right;">1428</td>
<td style="text-align: right;">128098</td>
</tr>
<tr class="even">
<td style="text-align: right;">2013</td>
<td style="text-align: right;">1539</td>
<td style="text-align: right;">137477</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2014</td>
<td style="text-align: right;">1620</td>
<td style="text-align: right;">144786</td>
</tr>
<tr class="even">
<td style="text-align: right;">2015</td>
<td style="text-align: right;">1663</td>
<td style="text-align: right;">146297</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2016</td>
<td style="text-align: right;">1725</td>
<td style="text-align: right;">149891</td>
</tr>
<tr class="even">
<td style="text-align: right;">2017</td>
<td style="text-align: right;">1738</td>
<td style="text-align: right;">151199</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2018</td>
<td style="text-align: right;">1756</td>
<td style="text-align: right;">148256</td>
</tr>
<tr class="even">
<td style="text-align: right;">2019</td>
<td style="text-align: right;">1771</td>
<td style="text-align: right;">147688</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">1649</td>
<td style="text-align: right;">136792</td>
</tr>
<tr class="even">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">1595</td>
<td style="text-align: right;">131451</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">1536</td>
<td style="text-align: right;">127270</td>
</tr>
<tr class="even">
<td style="text-align: right;">2023</td>
<td style="text-align: right;">1561</td>
<td style="text-align: right;">123977</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2024</td>
<td style="text-align: right;">1645</td>
<td style="text-align: right;">130223</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>postcodes_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="fu">here</span>(<span class="st">"data/raw/postcodes/postcodes.shp"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">suburb_name =</span> <span class="fu">case_when</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    mccid_int <span class="sc">==</span> <span class="dv">3000</span> <span class="sc">~</span> <span class="st">"Melbourne CBD"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    mccid_int <span class="sc">==</span> <span class="dv">3053</span> <span class="sc">~</span> <span class="st">"Carlton"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    mccid_int <span class="sc">==</span> <span class="dv">3008</span> <span class="sc">~</span> <span class="st">"Docklands"</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    mccid_int <span class="sc">==</span> <span class="dv">3002</span> <span class="sc">~</span> <span class="st">"East Melbourne"</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    mccid_int <span class="sc">==</span> <span class="dv">3031</span> <span class="sc">~</span> <span class="st">"Kensington"</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    mccid_int <span class="sc">==</span> <span class="dv">3051</span> <span class="sc">~</span> <span class="st">"North Melbourne"</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    mccid_int <span class="sc">==</span> <span class="dv">3052</span> <span class="sc">~</span> <span class="st">"Parkville"</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    mccid_int <span class="sc">==</span> <span class="dv">3006</span> <span class="sc">~</span> <span class="st">"Southbank"</span>,</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    mccid_int <span class="sc">==</span> <span class="dv">3141</span> <span class="sc">~</span> <span class="st">"South Yarra"</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    mccid_int <span class="sc">==</span> <span class="dv">3207</span> <span class="sc">~</span> <span class="st">"Port Melbourne"</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    mccid_int <span class="sc">==</span> <span class="dv">3003</span> <span class="sc">~</span> <span class="st">"West Melbourne"</span>,</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">""</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `postcodes' from data source 
  `/Users/suprithamaiya/Downloads/Semester4/WCD Assignment 4/data/raw/postcodes/postcodes.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 17 features and 8 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 144.897 ymin: -37.85066 xmax: 144.9913 ymax: -37.77545
Geodetic CRS:  WGS 84</code></pre>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>cafe_2002_sf <span class="ot">&lt;-</span> cafes <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Census year</span><span class="st">`</span> <span class="sc">==</span> <span class="dv">2002</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Longitude), <span class="sc">!</span><span class="fu">is.na</span>(Latitude)) <span class="sc">|&gt;</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"Longitude"</span>, <span class="st">"Latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>cafe_2024_sf <span class="ot">&lt;-</span> cafes <span class="sc">|&gt;</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Census year</span><span class="st">`</span> <span class="sc">==</span> <span class="dv">2024</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Longitude), <span class="sc">!</span><span class="fu">is.na</span>(Latitude)) <span class="sc">|&gt;</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"Longitude"</span>, <span class="st">"Latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>p2002 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> postcodes_sf, <span class="at">fill =</span> <span class="st">"grey95"</span>, <span class="at">colour =</span> <span class="st">"grey70"</span>, <span class="at">linewidth =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf_text</span>(<span class="at">data =</span> postcodes_sf, <span class="fu">aes</span>(<span class="at">label =</span> suburb_name), </span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">2</span>, <span class="at">colour =</span> <span class="st">"grey30"</span>) <span class="sc">+</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> cafe_2002_sf, <span class="fu">aes</span>(<span class="at">size =</span> <span class="st">`</span><span class="at">Number of seats</span><span class="st">`</span>), </span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>          <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">colour =</span> <span class="st">"#6F4E37"</span>) <span class="sc">+</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">8</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1300</span>)) <span class="sc">+</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">144.89</span>, <span class="fl">144.99</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">37.86</span>, <span class="sc">-</span><span class="fl">37.77</span>)) <span class="sc">+</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"2002"</span>, <span class="at">size =</span> <span class="st">"Seats"</span>) <span class="sc">+</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>p2024 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> postcodes_sf, <span class="at">fill =</span> <span class="st">"grey95"</span>, <span class="at">colour =</span> <span class="st">"grey70"</span>, <span class="at">linewidth =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf_text</span>(<span class="at">data =</span> postcodes_sf, <span class="fu">aes</span>(<span class="at">label =</span> suburb_name), </span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">2</span>, <span class="at">colour =</span> <span class="st">"grey30"</span>) <span class="sc">+</span></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> cafe_2024_sf, <span class="fu">aes</span>(<span class="at">size =</span> <span class="st">`</span><span class="at">Number of seats</span><span class="st">`</span>), </span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>          <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">colour =</span> <span class="st">"#6F4E37"</span>) <span class="sc">+</span></span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">8</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1300</span>)) <span class="sc">+</span></span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">144.89</span>, <span class="fl">144.99</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">37.86</span>, <span class="sc">-</span><span class="fl">37.77</span>)) <span class="sc">+</span></span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"2024"</span>, <span class="at">size =</span> <span class="st">"Seats"</span>) <span class="sc">+</span></span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>p2002 <span class="sc">+</span> p2024 <span class="sc">+</span></span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_annotation</span>(</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Café Seating Capacity Across Melbourne: 2002 vs 2024"</span>,</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment4_35196726_files/figure-html/spatial-map-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Total seating capacity more than doubled between 2002 and 2017, climbing from 85,349 to 151,199 seats. The spatial maps show cafés spreading further across the inner city by 2024, with larger concentrations appearing outside the CBD core compared to 2002.</p>
<p>But the growth story has a twist: the decline started before COVID. Seating was already falling from 2018 i.e.&nbsp;two years before the pandemic hit. And here’s what makes it stranger: the number of cafés kept rising until 2019, even as total seats fell.</p>
<p>This means that there were more venues but smaller ones. Way before COVID came into the picture, Melbourne’s cafes were possibly impacted by other factors such as rising rents, shifting dining habits, or merely market saturation.</p>
</section>
<section id="where-the-coffee-actually-is" class="level3">
<h3 class="anchored" data-anchor-id="where-the-coffee-actually-is">Where the coffee actually is</h3>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(suburb_2024, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(<span class="st">`</span><span class="at">CLUE small area</span><span class="st">`</span>, total_seats), </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">y =</span> total_seats)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#6F4E37"</span>) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Total Café Seating by Suburb (2024)"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Total Seats"</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment4_35196726_files/figure-html/suburb-bar-chart-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The CBD absolutely dominates when it comes to cafes as it holds more than four times the seating of Southbank, the next highest suburb. Southbank, Carlton, and Docklands form a distant second tier, and every other suburb barely has a presence.</p>
<p>Melbourne’s café culture, for all its citywide reputation, is really an inner-CBD story.</p>
</section>
<section id="the-impact-of-covid" class="level3">
<h3 class="anchored" data-anchor-id="the-impact-of-covid">The Impact of COVID</h3>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>covid_period <span class="ot">&lt;-</span> cafes <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Census year</span><span class="st">`</span> <span class="sc">&gt;=</span> <span class="dv">2018</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Census year</span><span class="st">`</span>, <span class="st">`</span><span class="at">Seating type</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_seats =</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">Number of seats</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(covid_period, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Census year</span><span class="st">`</span>, <span class="at">y =</span> total_seats, </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">colour =</span> <span class="st">`</span><span class="at">Seating type</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">2020</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">2020.2</span>, <span class="at">y =</span> <span class="fu">max</span>(covid_period<span class="sc">$</span>total_seats) <span class="sc">*</span> <span class="fl">0.95</span>,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"COVID-19"</span>, <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">3.5</span>) <span class="sc">+</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Seats - Indoor"</span> <span class="ot">=</span> <span class="st">"#6F4E37"</span>, </span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"Seats - Outdoor"</span> <span class="ot">=</span> <span class="st">"#D4A574"</span>)) <span class="sc">+</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">2018</span><span class="sc">:</span><span class="dv">2024</span>) <span class="sc">+</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Indoor vs Outdoor Café Seating Before and After COVID-19"</span>,</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Total Seats"</span>, <span class="at">colour =</span> <span class="st">"Seating Type"</span>) <span class="sc">+</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment4_35196726_files/figure-html/covid-seating-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Indoor seats fell sharply,from around 124,000 in 2019 to 110,000 by 2021. Outdoor seating barely moved across the same period. Both seating types declined in parallel, which rules out the simple narrative that venues adapted by shifting outdoors. If venues were pivoting to alfresco dining as a survival strategy, it isn’t visible here.</p>
<p>By 2024, indoor seating has partially recovered but remains below its pre-pandemic level. This current dataset cannot determine whether the pattern represents a permanent shift or a slow return to baseline.</p>
</section>
<section id="does-wealth-buy-you-better-café-access" class="level3">
<h3 class="anchored" data-anchor-id="does-wealth-buy-you-better-café-access">Does wealth buy you better café access?</h3>
<p>I expected wealthier suburbs to have more cafés. Despite the small sample size , the data says the opposite and the relationship is statistically significant (p = 0.013, R² = 0.55). Higher income is actually associated with fewer café seats per resident.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(equity_data, <span class="fu">aes</span>(<span class="at">x =</span> median_weekly_income, <span class="at">y =</span> seats_per_1000,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">label =</span> <span class="st">`</span><span class="at">CLUE small area</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">colour =</span> <span class="st">"#6F4E37"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">colour =</span> <span class="st">"#D4A574"</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  ggrepel<span class="sc">::</span><span class="fu">geom_text_repel</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Café Seats per 1,000 Residents vs Median Household Income (2024)"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Median Weekly Household Income ($)"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Café Seats per 1,000 Residents"</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment4_35196726_files/figure-html/equity-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>equity_data <span class="sc">|&gt;</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">CLUE small area</span><span class="st">`</span>, median_weekly_income, seats_per_1000) <span class="sc">|&gt;</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(median_weekly_income)) <span class="sc">|&gt;</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Suburb"</span>, <span class="st">"Median Weekly Income ($)"</span>, <span class="st">"Seats per 1,000 Residents"</span>),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">0</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Median weekly household income and café seats per 1,000 residents by suburb (2024)</caption>
<colgroup>
<col style="width: 36%">
<col style="width: 31%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Suburb</th>
<th style="text-align: right;">Median Weekly Income ($)</th>
<th style="text-align: right;">Seats per 1,000 Residents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Port Melbourne</td>
<td style="text-align: right;">2347</td>
<td style="text-align: right;">56</td>
</tr>
<tr class="even">
<td style="text-align: left;">East Melbourne</td>
<td style="text-align: right;">2345</td>
<td style="text-align: right;">412</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kensington</td>
<td style="text-align: right;">2216</td>
<td style="text-align: right;">118</td>
</tr>
<tr class="even">
<td style="text-align: left;">South Yarra</td>
<td style="text-align: right;">2078</td>
<td style="text-align: right;">27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Docklands</td>
<td style="text-align: right;">1956</td>
<td style="text-align: right;">818</td>
</tr>
<tr class="even">
<td style="text-align: left;">Southbank</td>
<td style="text-align: right;">1930</td>
<td style="text-align: right;">715</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Parkville</td>
<td style="text-align: right;">1885</td>
<td style="text-align: right;">296</td>
</tr>
<tr class="even">
<td style="text-align: left;">West Melbourne (Residential)</td>
<td style="text-align: right;">1784</td>
<td style="text-align: right;">225</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North Melbourne</td>
<td style="text-align: right;">1718</td>
<td style="text-align: right;">225</td>
</tr>
<tr class="even">
<td style="text-align: left;">Melbourne (CBD)</td>
<td style="text-align: right;">1319</td>
<td style="text-align: right;">1716</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Carlton</td>
<td style="text-align: right;">1289</td>
<td style="text-align: right;">825</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Port Melbourne ($2,347/week), East Melbourne ($2,345/week), and Kensington ($2,216/week) are the three wealthiest suburbs in this dataset — yet they have just 56, 412, and 118 café seats per 1,000 residents respectively. The CBD, by contrast, has a median income of $1,319/week but 1,716 seats per 1,000 residents. The café scene isn’t where people live richly. It’s where people pass through.</p>
</section>
<section id="tldr" class="level3">
<h3 class="anchored" data-anchor-id="tldr">TL;DR</h3>
<p>This analysis shows that three things stand out about Melbourne’s cafe culture.</p>
<ul>
<li>Growth peaked in 2017 and was already declining before COVID hit.</li>
<li>The scene is far more geographically concentrated than Melbourne’s reputation suggests.</li>
<li>Café access doesn’t follow residential wealth — it follows foot traffic.</li>
</ul>
<p>Melbourne’s café culture is real, but it’s actually operating in a pretty small radius.</p>
</section>
<section id="what-id-dig-into-next" class="level3">
<h3 class="anchored" data-anchor-id="what-id-dig-into-next">What I’d dig into next</h3>
<p>This analysis can further be extended by asking the following follow-up questions :</p>
<ul>
<li>Are larger venues replacing smaller ones, or are there simply fewer cafés overall?</li>
<li>Does the post-COVID recovery look different across suburbs?</li>
<li>Would overlaying public transport density explain the concentration better than income does?</li>
</ul>
</section>
<section id="references-1" class="level3">
<h3 class="anchored" data-anchor-id="references-1">References</h3>
<p>Müller K (2025). <em>here: A Simpler Way to Find Your Files</em>. R package version 1.0.2, <a href="https://CRAN.R-project.org/package=here" class="uri">https://CRAN.R-project.org/package=here</a>.</p>
<p>Pebesma, E., 2018. Simple Features for R: Standardized Support for Spatial Vector Data. The R Journal 10 (1), 439-446, <a href="https://doi.org/10.32614/RJ-2018-009" class="uri">https://doi.org/10.32614/RJ-2018-009</a></p>
<p>Pedersen T (2025). <em>patchwork: The Composer of Plots</em>. R package version 1.3.2, <a href="https://CRAN.R-project.org/package=patchwork" class="uri">https://CRAN.R-project.org/package=patchwork</a>.</p>
<p>Slowikowski K (2026). <em>ggrepel: Automatically Position Non-Overlapping Text Labels with ‘ggplot2’</em>. R package version 0.9.8, <a href="https://CRAN.R-project.org/package=ggrepel" class="uri">https://CRAN.R-project.org/package=ggrepel</a>.</p>
<p>Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G, Hayes A, Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller K, Ooms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K, Yutani H (2019). “Welcome to the tidyverse.” <em>Journal of Open Source Software</em>, <em>4</em>(43), 1686. doi:10.21105/joss.01686 <a href="https://doi.org/10.21105/joss.01686" class="uri">https://doi.org/10.21105/joss.01686</a>.</p>
<p>Wickham H, Bryan J (2025). <em>readxl: Read Excel Files</em>. R package version 1.4.5, <a href="https://CRAN.R-project.org/package=readxl" class="uri">https://CRAN.R-project.org/package=readxl</a>.</p>
<p>Xie Y (2024). <em>knitr: A General-Purpose Package for Dynamic Report Generation in R</em>. R package version 1.49, <a href="https://yihui.org/knitr/" class="uri">https://yihui.org/knitr/</a>.</p>
</section>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<section id="question-5" class="level3">
<h3 class="anchored" data-anchor-id="question-5">Question 5</h3>
<p><em>Tell us about parts of your data processing or analysis that weren’t “sexy” and wouldn’t typically be included in a blog post. (e.g.&nbsp;Was their any data drudgery or time intensive wrangling? Were there any repetitive tasks or manual tasks? If it was easy, describe what made it easy?)</em></p>
<p>As with assignment 2, the most tedious part of this analysis was reconciling two data sets that use two completely different geographic classifications.</p>
<p>The CLUE data uses City of Melbourne administrative boundaries, while ABS uses SA2 boundaries with entirely different names. This led to manually inspecting every suburb name in both data sets and constructing a look up table. SA2 was chosen as it is the ABS geographic unit that most closely approximates a suburb, and is the finest level at which median household income is published in the Census.</p>
<p>Also, the ABS metadata file added an another layer of complexity, I’d assumed the sheet would be named “SA2” but had to inspect all sheet names before finding the right one (“2021_ASGS_Main_Structures”).</p>
<p>A repetitive task that had to be carried out was to download both G02 and G01 files from the ABS website, as population counts were essential for calculating cafe seats per 1,000 residents, which is a useful metric for my last sub-question than total seats alone.</p>
<p>When CLUE small areas overlapped with multiple SA2 boundaries, median weekly income was estimated using a population-weighted mean. This was used as an approximation because individual-level income data was not available. The same method was applied across all affected suburbs, including Southbank, Melbourne CBD, and South Yarra.</p>
</section>
<section id="question-6" class="level3">
<h3 class="anchored" data-anchor-id="question-6">Question 6</h3>
<p><em>Were there any challenges that you faced in conducting this analysis. These may take the form of data limitations or coding challenges? (e.g.&nbsp;Was there anything in your analysis that you were not anticipating when you started? Did you have to change your intended scope? Did you need to master a new skill? Were there any problems you were proud of solving?)</em></p>
<p>I was surprised by how simple the CLUE dataset’s classifications were when compared to the ABS suburb boundaries. The Melbourne CBD, a single area according to the CLUE dataset, is split into 3 separate SA2s in the ABS data (Melbourne CBD East, North and West).Southbank is split across Southbank (West) - South Wharf and Southbank - East.South Yarra is split into three SA2s: South Yarra - West, South Yarra - North, and South Yarra - South.</p>
<p>“Melbourne (Remainder)” has no ABS equivalent at all and had to be excluded. For each split suburb, I calculated a population-weighted mean income across all constituent SA2s rather than arbitrarily picking one (which is what I started with but then I applied the same process across these three suburbs of CBD, Southbank and South Yarra) this added complexity but produced a more defensible result.</p>
<p>When I framed this question, I expected COVID to be the clear turning point. I didn’t anticipate that the pre-COVID decline in seating would predate 2020.The data showed seating already falling from 2018, which changed the framing of the entire growth section.</p>
</section>
<section id="question-7" class="level3">
<h3 class="anchored" data-anchor-id="question-7">Question 7</h3>
<p><em>Tell us about any imperfect parts of your work and how you would like to expand or improve this analysis in future? Be clear about any limitations or aspects of your analysis that fell beyond scope.</em></p>
<p>The equity analysis covers 11 of the 13 CLUE suburbs — “Melbourne (Remainder)” and “West Melbourne (Industrial)” could not be matched to ABS SA2s and were excluded. More significantly, the CLUE dataset covers only the City of Melbourne LGA, excluding inner suburbs like Fitzroy, Collingwood, and Richmond that are central to Melbourne’s actual café culture (Coffee on Cue, n.d.).Any equity conclusions are therefore limited to a narrow geographic slice of the city.</p>
<p>Again, as with assignment 2 - there is also a temporal mismatch.2021 Census income data paired with 2024 CLUE data means suburb demographics may have shifted in the intervening three years.</p>
<p>In future, I would expand the analysis to cover all of metropolitan Melbourne using a broader business register, use 2026 Census data once available, and overlay public transport accessibility as a potentially stronger predictor of café concentration than residential income.</p>
</section>
<section id="question-8" class="level3">
<h3 class="anchored" data-anchor-id="question-8">Question 8</h3>
<p><em>Tell us about how you used AI in your approach to your assignment. (e.g.&nbsp;Was AI consistently reliable? Did you provide AI with additional context? Was there anywhere where you questioned or verified the AI outputs? Was there anywhere we AI helped you learn something new?)</em></p>
<p>AI was useful for explaining topics such as coordinate reference systems, EPSG codes, and population-weighted means. However, I did not assume its responses were always correct and verified important information against official ABS documentation where necessary.</p>
<p>AI was used mainly as a troubleshooting and learning tool throughout the assignment. I provided detailed context, including code snippets, dataset structures, and intermediate outputs, to help diagnose problems and understand unfamiliar concepts.</p>
<p>Overall, AI served as a learning and troubleshooting resource, while the analysis, coding, interpretation, and writing were my own work.</p>
</section>
<section id="question-9" class="level3">
<h3 class="anchored" data-anchor-id="question-9">Question 9</h3>
<p><em>Submit 4 earlier versions of your .qmd files to show your iterative process. These versions must show iterations of your work (not just a linear progression of Task 1, Task 2, Task 3, citations). Reflect on the progress made between each versions by providing a short statement for markers of what you fixed/learnt/improved/changed between each file. Also like to reflect on what changed between your first checklist submission. (Note: There is an expectation for students familiar with GitHub that you will submit a Github repository and refer to 4 individual commits.)</em></p>
<p>My GitHub repository is at <a href="https://github.com/suprithamaiya/melbourne-cafe-analysis." class="uri">https://github.com/suprithamaiya/melbourne-cafe-analysis.</a></p>
<p>The commits document the iterative process:</p>
<ul>
<li>V1: Basic scaffolding — CLUE data loading, filtering, and initial charts. I was still exploring what to proceed with.</li>
<li>V2: Added equity analysis, suburb bar chart, scatter plot, regression, and references placeholders. Identified the geographic boundary mismatch as a challenge.</li>
<li>V3: I began to write the content once I had this structure and realized a lot of my initial assumptions about the data were incorrect.Restructured Task 1, made various code changes, completed blog post write-up.</li>
<li>V4: Improved spatial map with suburb boundary outlines and labels, expanded upon Question 4 according to all data sets used, added external data dictionary and sample files, updated README with correct file structure.</li>
</ul>
</section>
<section id="references-2" class="level3">
<h3 class="anchored" data-anchor-id="references-2">References</h3>
<p>Coffee on Cue. (n.d.). Melbourne’s best coffee suburbs outside the CBD. <a href="https://www.coffeeoncue.com.au/blogs/melbourne/melbourne-best-coffee-suburbs-outside-cbd" class="uri">https://www.coffeeoncue.com.au/blogs/melbourne/melbourne-best-coffee-suburbs-outside-cbd</a></p>
</section>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<p>AI was used mainly as a troubleshooting resource during my data exploration data processing.</p>
<p>In practice, I used AI to:</p>
<ul>
<li><p>Explain R functions and concepts needed to clean and tidy my data.</p></li>
<li><p>Provide general advice on coding approaches in R, which I then adapted and applied to my own dataset.</p></li>
</ul>
<p>The processing decisions, coding, and written submission were done by me.</p>
<p>Here is the link(s) to all prompts used :</p>
<p><a href="https://claude.ai/share/c17de840-6a74-43c1-be60-acf150806f24" class="uri">https://claude.ai/share/c17de840-6a74-43c1-be60-acf150806f24</a></p>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>